catalog/urls.py
from django.urls import path, include
from . import views

app_name = "catalog"

urlpatterns = [
    # For customers
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    path("products/", views.ProductListView.as_view(), name="products"),
    path("products/<int:pk>", views.ProductDetailView.as_view(), name="product-details"),
    path("products/search/", views.ProductSearchView.as_view(), name="product-search"),

    # For vendors
    path("vendors/login", views.vendors_login, name="vendors-login"),
    path("vendors/logout", views.vendors_logout, name="vendors-logout"),
    path("vendors/register", views.vendors_register, name="vendors-register"),
    path("vendors/products", views.VendorProductListView.as_view(), name="vendors-products"),
    path("vendors/products/add", views.ProductCreateView.as_view(), name="vendors-add-product"),
    path("vendors/products/edit/<int:pk>", views.ProductUpdateView.as_view(), name="vendors-edit-product"),
    path("vendors/products/delete/<int:pk>", views.ProductDeleteView.as_view(), name="vendors-delete-product"),
    path("vendors/profile", views.ProfileUpdateView.as_view(), name="vendors-profile")

]

shoppr/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),

    # Redirect the base URL to catalog app
    path('', RedirectView.as_view(url='catalog/'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from datetime import date

from django.db import models
from django.urls import reverse

# Create your models here.
class User(models.Model):
    ERROR_EMAIL_EXISTS = "A user with this email already exists."

    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(unique=True, error_messages={"unique": ERROR_EMAIL_EXISTS})
    password = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Vendor(models.Model):
    ERROR_EMAIL_EXISTS = "A user with this email already exists."

    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, error_messages={"unique": ERROR_EMAIL_EXISTS})
    password = models.CharField(max_length=128)
    address = models.TextField(default="")

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, blank=True, null=True)
    price = models.FloatField()
    stock = models.IntegerField(default=0)
    photo = models.ImageField(upload_to="images/products", blank=True, null=True)

    def __str__(self):
        return self.title
    

    def format_price(self):
        return f"₹{self.price:,.0f}"
    

    def get_absolute_url(self):
        return reverse("catalog:product-details", args=[self.id])


    def get_edit_url(self):
        return reverse("catalog:vendors-edit-product", args=[self.id])


    def get_delete_url(self):
        return reverse("catalog:vendors-delete-product", args=[self.id])

catalog/forms.py
from django import forms
from . import models

class RegisterForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["first_name", "last_name", "email", "password"]

    # Additional password field for confirmation
    conf_password = forms.CharField(max_length=128)

    widgets = {
        "password": forms.PasswordInput(),
        "conf_password": forms.PasswordInput()
    }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data["password"]
        conf_password = cleaned_data["conf_password"]

        if password != conf_password:
            raise forms.ValidationError("The passwords don't match.")


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(max_length=128)


class VendorRegisterForm(forms.ModelForm):
    class Meta:
        model = models.Vendor
        fields = ["name", "email", "address", "password"]

    # Additional password field for confirmation
    conf_password = forms.CharField(max_length=128)

    widgets = {
        "password": forms.PasswordInput(),
        "conf_password": forms.PasswordInput()
    }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data["password"]
        conf_password = cleaned_data["conf_password"]

        if password != conf_password:
            raise forms.ValidationError("The passwords don't match.")


class VendorLoginForm(LoginForm):
    pass

catalog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.db.models import Q

from .models import User, Product, Vendor
from .forms import RegisterForm, LoginForm, VendorLoginForm, VendorRegisterForm

# Create your views here.
def index(request):
    if "user" in request.session:
        return HttpResponseRedirect(reverse("catalog:products"))
    else:
        return render(request, 'catalog/index.html')


def login(request):
    # Redirect, if already logged in.
    if "user" in request.session:
        return HttpResponseRedirect(reverse("catalog:products"))

    if request.method == "POST":
        form = LoginForm(request.POST, auto_id=False)

        if form.is_valid():
            user = are_credentials_valid(
                form.cleaned_data["email"], 
                form.cleaned_data["password"],
                User)
            if user:
                # Create a session
                request.session["user"] = user.id
                return HttpResponseRedirect(reverse("catalog:products"))
            else:
                messages.error(request, "Incorrect email or password!")
        else:
            messages.error(request, "Invalid form!")
    else:
        form = LoginForm(auto_id=False)

    return render(request, "catalog/login.html", {"form": form})


def logout(request):
    try:
        del request.session["user"]
    except KeyError:
        pass
    return HttpResponseRedirect(reverse("catalog:index"))


def register(request):
    # Redirect, if already logged in.
    if "user" in request.session:
        return HttpResponseRedirect(reverse("catalog:products"))

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            # Save the form data
            form.save()

            # Redirect to Login page
            messages.success(request, "Registration complete! Login to continue.")
            return HttpResponseRedirect(reverse("catalog:login"))
    else:
        form = RegisterForm(auto_id=False)

    return render(request, "catalog/register.html", {"form": form})


def are_credentials_valid(email, password, model):
    result = model.objects.filter(email=email)

    # Check if a user with submitted email exists or not
    if result:
        user = result.first()

        # Check if password is valid
        if user.password == password:
            return user
        else:
            return False
    else:
        # Invalid email address
        return False


# Generic class-based views
class ProductListView(ListView):
    queryset = Product.objects.order_by("title")

    def dispatch(self, request, *args, **kwargs):
        if not "user" in request.session:
            return HttpResponseRedirect(reverse("catalog:index"))
        else:
            return super().dispatch(request, *args, **kwargs)


class ProductDetailView(DetailView):
    model = Product

    def dispatch(self, request, *args, **kwargs):
        if not "user" in request.session:
            return HttpResponseRedirect(reverse("catalog:index"))
        else:
            return super().dispatch(request, *args, **kwargs)


class ProductSearchView(ListView):
    model = Product
    template_name = "catalog/search.html"

    def get_queryset(self):
        # Get the query string
        q = self.request.GET.get('q', '')

        if q:
            query = Q(title__icontains=q) | Q(description__icontains=q) | Q(price__icontains=q)
            return self.model.objects.filter(query)
        else:
            return None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context
    
    def dispatch(self, request, *args, **kwargs):
        if not "user" in request.session:
            return HttpResponseRedirect(reverse("catalog:index"))
        else:
            return super().dispatch(request, *args, **kwargs)


# Vendor's product views
class VendorProductListView(ListView):
    template_name = "catalog/vendors/products.html"

    def get_queryset(self):
        vendor = Vendor.objects.get(pk=self.request.session["vendor"])
        return Product.objects.filter(vendor=vendor)

    def dispatch(self, request, *args, **kwargs):
        if not "vendor" in request.session:
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
        else:
            return super().dispatch(request, *args, **kwargs)


def vendors_login(request):
    # Redirect, if already logged in.
    if "vendor" in request.session:
        return HttpResponseRedirect(reverse("catalog:vendors-products"))

    if request.method == "POST":
        form = VendorLoginForm(request.POST, auto_id=False)

        if form.is_valid():
            vendor = are_credentials_valid(
                form.cleaned_data["email"], 
                form.cleaned_data["password"],
                Vendor)
            if vendor:
                # Create a session
                request.session["vendor"] = vendor.id
                return HttpResponseRedirect(reverse("catalog:vendors-products"))
            else:
                messages.error(request, "Incorrect email or password!")
        else:
            messages.error(request, "Invalid form!")
    else:
        form = VendorLoginForm(auto_id=False)

    return render(request, "catalog/vendors/login.html", {"form": form})


def vendors_register(request):
    # Redirect, if already logged in.
    if "vendor" in request.session:
        return HttpResponseRedirect(reverse("catalog:vendor-products"))

    if request.method == "POST":
        form = VendorRegisterForm(request.POST)

        if form.is_valid():
            # Save the form data
            form.save()

            # Redirect to Login page
            messages.success(request, "Registration complete! Login to continue.")
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
    else:
        form = VendorRegisterForm(auto_id=False)

    return render(request, "catalog/vendors/register.html", {"form": form})


def vendors_logout(request):
    try:
        del request.session["vendor"]
    except KeyError:
        pass
    return HttpResponseRedirect(reverse("catalog:vendors-login"))



# CRUD Views
from django.urls import reverse_lazy
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

class ProductBaseView(FormView):
    model = Product
    fields = ["title", "description", "stock", "price", "photo"]
    success_url = reverse_lazy("catalog:vendors-products")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["auto_id"] = False
        return kwargs


    def dispatch(self, request, *args, **kwargs):
        if not "vendor" in request.session:
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
        else:
            return super().dispatch(request, *args, **kwargs)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class ProductCreateView(ProductBaseView, CreateView):
    template_name = "catalog/vendors/product_form.html"

    def form_valid(self, form):
        # Add the current vendor to the new product
        vendor = Vendor.objects.get(pk=self.request.session["vendor"])
        form.instance.vendor = vendor
        return super().form_valid(form)
    

class ProductUpdateView(ProductBaseView, UpdateView):
    template_name = "catalog/vendors/product_form.html"


class ProductDeleteView(ProductBaseView, DeleteView):
    template_name = "catalog/vendors/product_confirm_delete.html"


class ProfileUpdateView(UpdateView):
    model = Vendor
    fields = ["name", "email", "address", "password"]
    success_url = reverse_lazy("catalog:vendors-profile")
    template_name = "catalog/vendors/profile.html"

    def get_object(self):
        return Vendor.objects.get(pk=self.request.session["vendor"])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["auto_id"] = False
        return kwargs

    def dispatch(self, request, *args, **kwargs):
        if not "vendor" in request.session:
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
        else:
            return super().dispatch(request, *args, **kwargs)

catalog/templates/catalog/vendors/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% block title %}
    <title>
      {% block page-title %}<!--e.g. Home-->{% endblock %} - Shoppr for Vendors
    </title>
    {% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <!-- Bootstrap with customizations -->
    <link rel="stylesheet" href="{% static 'catalog/css/vendors/custom.css' %}">

    <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">

    {% block styles %}<!-- Custom CSS per page -->{% endblock %}
  </head>

  <body>
    <header class="bg-primary">
      <div class="container">
        <nav class="navbar navbar-expand-md navbar-dark">
          <a href="{% url 'catalog:vendors-login' %}" class="navbar-brand h1">
            Shoppr <span class="lead">for vendors</span>
          </a>
          <ul class="navbar-nav ms-auto">
            <li><a href="#" class="nav-link">About</a></li>
            {% block extra_links %}<!-- Extra page specific links -->{% endblock %}
          </ul>

          {% block extra_items %}<!-- Some extra items on the navbar -->{% endblock %}
        </nav>
      </div>
    </header>

    <main>
      <div class="container">
        {% if vendor %}
          <p class="lead fs-4 text-end">Welcome, <span class="fw-bold">{{ vendor.name }}</span></p>
          <hr>
        {% endif %}

        {% block content %} {% endblock %}
      </div>
    </main>

    <footer class="bg-light py-4 text-center">
      <div class="container">
        <p class="lead mb-1">Made with ❤️ in Python + HTML & CSS</p>
        <p class="mb-0">&copy; Copyright 2022 Shoppr</p>
      </div>
    </footer>
  </body>

</html>

catalog/templates/catalog/vendors/login.html
{% extends "catalog/vendors/base.html" %}

{% block page-title %} Login {% endblock %}

{% block content %}
  <div class="messages">
    {% if messages %}
      {% for message in messages %}
      <p class="fs-5 text-secondary">{{ message }}</p>
      {% endfor %}
    {% endif %}
  </div>

  <h1>Login</h1>  
  <p class="lead">Welcome back!</p>

  <form class="mt-4" action="{% url 'catalog:vendors-login' %}" method="post">
    {% csrf_token %}

    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-md-6 col-lg-5 mb-3">
          <label for="email" class="form-label">Email</label>
          <input type="email" class="form-control " name="{{ form.email.html_name }}" id="email" placeholder="e.g. abc@example.com" value="{{ form.email.value|default:'' }}" required>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-6 col-lg-5 mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control " name="{{ form.password.html_name }}" id="password" value="{{ form.password.value|default:'' }}" required>
        </div>
      </div>
    </div>

    <div class="mb-2">
      <button class="btn btn-primary">Login</button>
    </div>

    <p>New to Shoppr? <a href="{% url 'catalog:vendors-register' %}" class="link-primary">Register</a></p>
  </form>
{% endblock %}

catalog/templates/catalog/vendors/product_confirm_delete.html
{% extends "catalog/vendors/base.html" %}

{% block page-title %} Delete a product {% endblock %}

{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'catalog/css/vendors/products.css' %}">
{% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:vendors-products' %}" class="nav-link active">Products</a></li>
  <li><a href="#" class="nav-link">Profile</a></li>
  <li><a href="{% url 'catalog:vendors-logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block content %}
  <section>
    <p class="fs-3">Are you sure you want to delete this product?</p>

    <table class="table mt-3">
      <thead>
        <tr>
          <th>Title</th>
          <th>Image</th>
          <th>Price</th>
          <th>Stock</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <tr>
          <td>{{ product.title }}</td>
          <td class="py-3">
            {% if product.photo %}
              <img src="{{ product.photo.url }}" alt="{{ product.title.value }}">
            {% else %}
              No photo
            {% endif %}
          </td>
          <td>{{ product.format_price }}</td>
          <td>{{ product.stock }}</td>
        </tr>
      </tbody>
    </table>

    <form action="{{ product.get_delete_url }}" method="POST">
      {% csrf_token %}
      
      <button class="btn btn-danger me-2">Delete</button>
      <a href="{% url 'catalog:vendors-products' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </section>
{% endblock %}

catalog/templates/catalog/vendors/product_form.html
{% extends "catalog/vendors/base.html" %}

{% block page-title %} {% if product %}Edit{% else %}Add{% endif %} a product {% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:vendors-products' %}" class="nav-link active">Products</a></li>
  <li><a href="{% url 'catalog:vendors-profile' %}" class="nav-link">Profile</a></li>
  <li><a href="{% url 'catalog:vendors-logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block content %}
<h1>
  {% if product %}Edit{% else %}Add{% endif %} a product
</h1>  
  
  <form class="mt-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="title" class="form-label">Title</label>
          <input type="text" class="form-control" name="{{ form.title.html_name }}" id="title" placeholder="e.g. Running Shoes" value="{{ form.title.value|default:'' }}" required>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="price" class="form-label">Price</label>
          <input type="number" class="form-control" name="{{ form.price.html_name }}" id="price" placeholder="e.g. 800" value="{{ form.price.value|default:'' }}" required>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="description" class="form-label">Description</label>
          <textarea class="form-control" name="{{ form.description.html_name }}" id="description" placeholder="Enter your product's description">{{ form.description.value|default:'' }}</textarea>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="stock" class="form-label">Stock</label>
          <input type="number" class="form-control" name="{{ form.stock.html_name }}" id="stock" placeholder="e.g. 20" value="{{ form.stock.value|default:'' }}" required>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="photo" class="form-label">Photo</label>

          {% if product.photo %}
            <img src="{{ product.photo.url }}" alt="form.title" style="width: 100px;" class="d-block mb-3">
          {% endif%}
          
          <input type="file" class="form-control" name="{{ form.photo.html_name }}" accept="image/*" id="photo">
        </div>
      </div>
    </div>
   
    <div class="my-2">
      <button class="btn btn-primary me-2">Save</button>
      <a class="btn btn-secondary" href="{% url 'catalog:vendors-products' %}">Cancel</a>
    </div>

  </form>
{% endblock %}

catalog/templates/catalog/vendors/products.html
{% extends "catalog/vendors/base.html" %}

{% block page-title %} Your Products {% endblock %}

{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'catalog/css/vendors/products.css' %}">
{% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:vendors-products' %}" class="nav-link active">Products</a></li>
  <li><a href="{% url 'catalog:vendors-profile' %}" class="nav-link">Profile</a></li>
  <li><a href="{% url 'catalog:vendors-logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block content %}
  <section>
    <div class="mt-5 d-flex justify-content-between align-items-center">
      <h1 class="h4 m-0">Product Details</h1>
      <a href="{% url 'catalog:vendors-add-product' %}" class="btn btn-info">Add Product</a>
    </div>

    <table class="table mt-3">
      <thead>
        <tr>
          <th>No.</th>
          <th>Title</th>
          <th>Image</th>
          <th>Price</th>
          <th>Stock</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% if product_list %}
          {% for product in product_list %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ product.title }}</td>
              <td class="py-3">
                {% if product.photo %}
                  <img src="{{ product.photo.url }}" alt="{{ product.title }}">
                {% else %}
                  No Photo
                {% endif %}
              </td>
              <td>{{ product.format_price }}</td>
              <td class="fit">{{ product.stock }}</td>
              <td class="text-end">
                <a href="{{ product.get_edit_url }}" class="ms-1 btn btn-sm btn-secondary">Edit</a>
                <a href="{{ product.get_delete_url }}" class="ms-1 btn btn-sm btn-danger">Delete</a>
              </td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="5" class="text-center text-secondary fs-5">No products are available!</td>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </section>
{% endblock %}

catalog/templates/catalog/vendors/profile.html
{% extends "catalog/vendors/base.html" %}

{% block page-title %} Profile {% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:vendors-products' %}" class="nav-link">Products</a></li>
  <li><a href="{% url 'catalog:vendors-profile' %}" class="nav-link active">Profile</a></li>
  <li><a href="{% url 'catalog:vendors-logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block content %}
  <h1 class="mb-4">Your Profile</h1>
  
  <form class="mt-4" method="post">
    {% csrf_token %}
    
    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="name" class="form-label">Name</label>
          <input type="text" class="form-control" name="{{ form.name.html_name }}" id="name" placeholder="e.g. XYZ Incorporated" value="{{ form.name.value|default:'' }}" required>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="email" class="form-label">Email</label>
          <input type="email" class="form-control" name="{{ form.email.html_name }}" id="email" placeholder="e.g. abc@example.com" value="{{ form.email.value|default:'' }}" required>

          {% if form.email.errors %}
            {% for error in form.email.errors %}
              <p class="form-text text-danger">{{ error }}</p>
            {% endfor %}
          {% endif %}
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="address" class="form-label">Address</label>
          <textarea class="form-control" name="{{ form.address.html_name }}" id="address" placeholder="Enter your company's address">{{ form.address.value|default:'' }}</textarea>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" name="{{ form.password.html_name }}" id="password" value="{{ form.password.value|default:'' }}" required>
        </div>
      </div>
    </div>
   
    <div class="mb-2">
      <button class="btn btn-primary">Save</button>
    </div>

  </form>
{% endblock %}

catalog/templates/catalog/vendors/register.html
{% extends "catalog/vendors/base.html" %}

{% block page-title %} Get Started {% endblock %}

{% block content %}
<h1>Register</h1>  
<p class="lead">Start selling products with Shoppr</p>
  
  <form class="mt-4" action="{% url 'catalog:vendors-register' %}" method="post">
    {% csrf_token %}
    
    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="name" class="form-label">Name</label>
          <input type="text" class="form-control" name="{{ form.name.html_name }}" id="name" placeholder="e.g. XYZ Incorporated" value="{{ form.name.value|default:'' }}" required>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="email" class="form-label">Email</label>
          <input type="email" class="form-control" name="{{ form.email.html_name }}" id="email" placeholder="e.g. abc@example.com" value="{{ form.email.value|default:'' }}" required>

          {% if form.email.errors %}
            {% for error in form.email.errors %}
              <p class="form-text text-danger">{{ error }}</p>
            {% endfor %}
          {% endif %}
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="address" class="form-label">Address</label>
          <textarea class="form-control" name="{{ form.address.html_name }}" id="address" placeholder="Enter your company's address">
            {{ form.address.value|default:'' }}
          </textarea>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" name="{{ form.password.html_name }}" id="password" value="{{ form.password.value|default:'' }}" required>
          
          {% for error in form.non_field_errors %}
            <p class="form-text text-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="conf-password" class="form-label">Re-enter your password</label>
          <input type="password" class="form-control" name="{{ form.conf_password.html_name }}" id="conf-password" value="{{ form.conf_password.value|default:'' }}" required>
        </div>
      </div>
    </div>
   
    <div class="mb-2">
      <button class="btn btn-primary">Register</button>
    </div>

    <p>Already registered? <a href="{% url 'catalog:vendors-login' %}" class="link-primary">Login</a></p>
  </form>
{% endblock %}