catalog/urls.py
from django.urls import path, include
from . import views

app_name = "catalog"

urlpatterns = [
    # For customers
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    path("products/", views.ProductListView.as_view(), name="products"),
    path("products/<int:pk>", views.ProductDetailView.as_view(), name="product-details"),
    path("products/search/", views.ProductSearchView.as_view(), name="product-search"),

    # For vendors
    path("vendors/login", views.vendors_login, name="vendors-login"),
    path("vendors/logout", views.vendors_logout, name="vendors-logout"),
    path("vendors/register", views.vendors_register, name="vendors-register"),
    path("vendors/products", views.VendorProductListView.as_view(), name="vendors-products"),
    path("vendors/products/add", views.ProductCreateView.as_view(), name="vendors-add-product"),
    path("vendors/products/edit/<int:pk>", views.ProductUpdateView.as_view(), name="vendors-edit-product"),
    path("vendors/products/delete/<int:pk>", views.ProductDeleteView.as_view(), name="vendors-delete-product"),
    path("vendors/profile", views.ProfileUpdateView.as_view(), name="vendors-profile")

]

shoppr/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),

    # Redirect the base URL to catalog app
    path('', RedirectView.as_view(url='catalog/'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from datetime import date

from django.db import models
from django.urls import reverse

# Create your models here.
class User(models.Model):
    ERROR_EMAIL_EXISTS = "A user with this email already exists."

    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(unique=True, error_messages={"unique": ERROR_EMAIL_EXISTS})
    password = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Vendor(models.Model):
    ERROR_EMAIL_EXISTS = "A user with this email already exists."

    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, error_messages={"unique": ERROR_EMAIL_EXISTS})
    password = models.CharField(max_length=128)
    address = models.TextField(default="")

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, blank=True, null=True)
    price = models.FloatField()
    stock = models.IntegerField(default=0)
    photo = models.ImageField(upload_to="images/products", blank=True, null=True)

    def __str__(self):
        return self.title
    

    def format_price(self):
        return f"₹{self.price:,.0f}"
    

    def get_absolute_url(self):
        return reverse("catalog:product-details", args=[self.id])


    def get_edit_url(self):
        return reverse("catalog:vendors-edit-product", args=[self.id])


    def get_delete_url(self):
        return reverse("catalog:vendors-delete-product", args=[self.id])

catalog/forms.py
from django import forms
from . import models

class RegisterForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["first_name", "last_name", "email", "password"]

    # Additional password field for confirmation
    conf_password = forms.CharField(max_length=128)

    widgets = {
        "password": forms.PasswordInput(),
        "conf_password": forms.PasswordInput()
    }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data["password"]
        conf_password = cleaned_data["conf_password"]

        if password != conf_password:
            raise forms.ValidationError("The passwords don't match.")


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(max_length=128)


class VendorRegisterForm(forms.ModelForm):
    class Meta:
        model = models.Vendor
        fields = ["name", "email", "address", "password"]

    # Additional password field for confirmation
    conf_password = forms.CharField(max_length=128)

    widgets = {
        "password": forms.PasswordInput(),
        "conf_password": forms.PasswordInput()
    }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data["password"]
        conf_password = cleaned_data["conf_password"]

        if password != conf_password:
            raise forms.ValidationError("The passwords don't match.")


class VendorLoginForm(LoginForm):
    pass

catalog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.db.models import Q

from .models import User, Product, Vendor
from .forms import RegisterForm, LoginForm, VendorLoginForm, VendorRegisterForm

# Create your views here.
def index(request):
    if "user" in request.session:
        return HttpResponseRedirect(reverse("catalog:products"))
    else:
        return render(request, 'catalog/index.html')


def login(request):
    # Redirect, if already logged in.
    if "user" in request.session:
        return HttpResponseRedirect(reverse("catalog:products"))

    if request.method == "POST":
        form = LoginForm(request.POST, auto_id=False)

        if form.is_valid():
            user = are_credentials_valid(
                form.cleaned_data["email"], 
                form.cleaned_data["password"],
                User)
            if user:
                # Create a session
                request.session["user"] = user.id
                return HttpResponseRedirect(reverse("catalog:products"))
            else:
                messages.error(request, "Incorrect email or password!")
        else:
            messages.error(request, "Invalid form!")
    else:
        form = LoginForm(auto_id=False)

    return render(request, "catalog/login.html", {"form": form})


def logout(request):
    try:
        del request.session["user"]
    except KeyError:
        pass
    return HttpResponseRedirect(reverse("catalog:index"))


def register(request):
    # Redirect, if already logged in.
    if "user" in request.session:
        return HttpResponseRedirect(reverse("catalog:products"))

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            # Save the form data
            form.save()

            # Redirect to Login page
            messages.success(request, "Registration complete! Login to continue.")
            return HttpResponseRedirect(reverse("catalog:login"))
    else:
        form = RegisterForm(auto_id=False)

    return render(request, "catalog/register.html", {"form": form})


def are_credentials_valid(email, password, model):
    result = model.objects.filter(email=email)

    # Check if a user with submitted email exists or not
    if result:
        user = result.first()

        # Check if password is valid
        if user.password == password:
            return user
        else:
            return False
    else:
        # Invalid email address
        return False


# Generic class-based views
class ProductListView(ListView):
    queryset = Product.objects.order_by("title")

    def dispatch(self, request, *args, **kwargs):
        if not "user" in request.session:
            return HttpResponseRedirect(reverse("catalog:index"))
        else:
            return super().dispatch(request, *args, **kwargs)


class ProductDetailView(DetailView):
    model = Product

    def dispatch(self, request, *args, **kwargs):
        if not "user" in request.session:
            return HttpResponseRedirect(reverse("catalog:index"))
        else:
            return super().dispatch(request, *args, **kwargs)


class ProductSearchView(ListView):
    model = Product
    template_name = "catalog/search.html"

    def get_queryset(self):
        # Get the query string
        q = self.request.GET.get('q', '')

        if q:
            query = Q(title__icontains=q) | Q(description__icontains=q) | Q(price__icontains=q)
            return self.model.objects.filter(query)
        else:
            return None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context
    
    def dispatch(self, request, *args, **kwargs):
        if not "user" in request.session:
            return HttpResponseRedirect(reverse("catalog:index"))
        else:
            return super().dispatch(request, *args, **kwargs)


# Vendor's product views
class VendorProductListView(ListView):
    template_name = "catalog/vendors/products.html"

    def get_queryset(self):
        vendor = Vendor.objects.get(pk=self.request.session["vendor"])
        return Product.objects.filter(vendor=vendor)

    def dispatch(self, request, *args, **kwargs):
        if not "vendor" in request.session:
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
        else:
            return super().dispatch(request, *args, **kwargs)


def vendors_login(request):
    # Redirect, if already logged in.
    if "vendor" in request.session:
        return HttpResponseRedirect(reverse("catalog:vendors-products"))

    if request.method == "POST":
        form = VendorLoginForm(request.POST, auto_id=False)

        if form.is_valid():
            vendor = are_credentials_valid(
                form.cleaned_data["email"], 
                form.cleaned_data["password"],
                Vendor)
            if vendor:
                # Create a session
                request.session["vendor"] = vendor.id
                return HttpResponseRedirect(reverse("catalog:vendors-products"))
            else:
                messages.error(request, "Incorrect email or password!")
        else:
            messages.error(request, "Invalid form!")
    else:
        form = VendorLoginForm(auto_id=False)

    return render(request, "catalog/vendors/login.html", {"form": form})


def vendors_register(request):
    # Redirect, if already logged in.
    if "vendor" in request.session:
        return HttpResponseRedirect(reverse("catalog:vendor-products"))

    if request.method == "POST":
        form = VendorRegisterForm(request.POST)

        if form.is_valid():
            # Save the form data
            form.save()

            # Redirect to Login page
            messages.success(request, "Registration complete! Login to continue.")
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
    else:
        form = VendorRegisterForm(auto_id=False)

    return render(request, "catalog/vendors/register.html", {"form": form})


def vendors_logout(request):
    try:
        del request.session["vendor"]
    except KeyError:
        pass
    return HttpResponseRedirect(reverse("catalog:vendors-login"))



# CRUD Views
from django.urls import reverse_lazy
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

class ProductBaseView(FormView):
    model = Product
    fields = ["title", "description", "stock", "price", "photo"]
    success_url = reverse_lazy("catalog:vendors-products")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["auto_id"] = False
        return kwargs


    def dispatch(self, request, *args, **kwargs):
        if not "vendor" in request.session:
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
        else:
            return super().dispatch(request, *args, **kwargs)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class ProductCreateView(ProductBaseView, CreateView):
    template_name = "catalog/vendors/product_form.html"

    def form_valid(self, form):
        # Add the current vendor to the new product
        vendor = Vendor.objects.get(pk=self.request.session["vendor"])
        form.instance.vendor = vendor
        return super().form_valid(form)
    

class ProductUpdateView(ProductBaseView, UpdateView):
    template_name = "catalog/vendors/product_form.html"


class ProductDeleteView(ProductBaseView, DeleteView):
    template_name = "catalog/vendors/product_confirm_delete.html"


class ProfileUpdateView(UpdateView):
    model = Vendor
    fields = ["name", "email", "address", "password"]
    success_url = reverse_lazy("catalog:vendors-profile")
    template_name = "catalog/vendors/profile.html"

    def get_object(self):
        return Vendor.objects.get(pk=self.request.session["vendor"])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["auto_id"] = False
        return kwargs

    def dispatch(self, request, *args, **kwargs):
        if not "vendor" in request.session:
            return HttpResponseRedirect(reverse("catalog:vendors-login"))
        else:
            return super().dispatch(request, *args, **kwargs)

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% block title %}
    <title>
      {% block page-title %}<!--e.g. Home-->{% endblock %} - Shoppr
    </title>
    {% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <!-- Bootstrap with customizations -->
    <link rel="stylesheet" href="{% static 'catalog/css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">

    {% block styles %}<!-- Custom CSS per page -->{% endblock %}
  </head>

  <body>
    <header class="bg-primary">
      <div class="container">
        <nav class="navbar navbar-expand-md navbar-dark">
          <a href="/" class="navbar-brand h1">Shoppr</a>
          <ul class="navbar-nav ms-auto">
            <li><a href="{% url 'catalog:index' %}" class="nav-link">Home</a></li>
            <li><a href="#" class="nav-link">About</a></li>
            {% block extra_links %}<!-- Extra page specific links -->{% endblock %}
          </ul>

          {% block extra_items %}<!-- Some extra items on the navbar -->{% endblock %}
        </nav>
      </div>
    </header>

    <main>
      <div class="container">
        {% if sh_user %}
          <p class="lead fs-4 text-end">Welcome, <span class="fw-bold">{{ sh_user }}</span></p>
          <hr>
        {% endif %}

        {% block content %} {% endblock %}
      </div>
    </main>

    <footer class="bg-light py-4 text-center">
      <div class="container">
        <p class="lead mb-1">Made with ❤️ in Python + HTML & CSS</p>
        <p class="mb-0">&copy; Copyright 2022 Shoppr</p>
      </div>
    </footer>
  </body>

</html>

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block page-title %} Home {% endblock %}

{% block content %}
  <div class="text-center p-5 bg-light rounded">
    <h1 class="display-5 fw-bold mb-4 text-primary">Welcome to Shoppr</h1>
    <p class="fs-4">
      An e-commerce site for perfectionists with deadlines. <br>
      A single place for customers and vendors alike.
    </p>

    <p class="lead fs-4 mt-4">Who are you?</p>
    <div class="d-flex justify-content-center gap-3">
      <a href="{% url 'catalog:login' %}" class="btn btn-primary">Customer</a>
      <a href="{% url 'catalog:vendors-login' %}" class="btn btn-accent">Vendor</a>
    </div>
  </div>

  <!-- <div class="mt-4">
    <a href="{% url 'catalog:register' %}" class="btn btn-primary me-2">Get Started</a>
    <a href="{% url 'catalog:login' %}" class="btn btn-secondary me-2">Login</a>
  </div>   -->
{% endblock %}

catalog/templates/catalog/login.html
{% extends "catalog/base_generic.html" %}

{% block page-title %} Login {% endblock %}

{% block content %}
  <div class="messages">
    {% if messages %}
      {% for message in messages %}
      <p class="fs-5 text-secondary">{{ message }}</p>
      {% endfor %}
    {% endif %}
  </div>

  <h1 class="mb-4">Login</h1>  

  <form action="{% url 'catalog:login' %}" method="post">
    {% csrf_token %}

    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-md-6 col-lg-5 mb-3">
          <label for="email" class="form-label">Email</label>
          <input type="email" class="form-control " name="{{ form.email.html_name }}" id="email" placeholder="e.g. abc@example.com" value="{{ form.email.value|default:'' }}" required>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-6 col-lg-5 mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control " name="{{ form.password.html_name }}" id="password" value="{{ form.password.value|default:'' }}" required>
        </div>
      </div>
    </div>

    <div class="mb-2">
      <button class="btn btn-primary">Login</button>
    </div>

    <p>New to Shoppr? <a href="{% url 'catalog:register' %}" class="link-primary">Register</a></p>
  </form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends "catalog/base_generic.html" %}

{% block page-title %} {{ product.title }} {% endblock %}

{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'catalog/css/product_detail.css' %}">
{% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block extra_items %}
{% include "catalog/search_form.html" %}
{% endblock %}

{% block content %}
  <section>
    <div class="row gy-4">
      <!-- Image -->
      <div class="col-12 col-md-6 order-md-1 text-center img-ctn">
          <img class="img-fluid" src="{{ product.photo.url }}" alt="{{ product.title }} image">
      </div>

      <!-- Product details -->
      <div class="col-12 col-md-6 order-md-0">
        <h1>{{ product.title }}</h1>
        <p class="fs-4 text-primary">{{ product.format_price }}</p>
        <button class="btn btn-primary">Add to Cart</button>

        <section class="mt-5">
          <h2 class="fs-5">About this item</h2>
          <div class="description">
            {{ product.description|linebreaks }}
          </div>
        </section>
      </div>
    </div>
  </section>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "catalog/base_generic.html" %}

{% block page-title %} Catalog {% endblock %}

{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'catalog/css/products.css' %}">
{% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block extra_items %}
{% include "catalog/search_form.html" %}
{% endblock %}

{% block content %}
  <section>
    <h1>All Products</h1>
    
    <p class="lead">You can find all products available on Shoppr.</p>

    {% if product_list %}
    <div class="container my-5">
      
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-2 g-lg-3">
        
        {% for product in product_list %}
        <div class="col">
          <div class="card">
            <a href="{{ product.get_absolute_url }}">
              <img class="card-img-top p-2" src="{{ product.photo.url }}" alt="{{ product.title }}">
            </a>
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <h2 class="card-title h5 m-0">
                  <a href="{{ product.get_absolute_url }}" class="link-dark text-decoration-none">{{ product.title }}</a>
                </h2>
                <p class="card-text text-primary lead fw-bold">{{ product.format_price }}</p>
              </div>
              <button class="btn btn-outline-secondary btn-sm w-100">Add to Cart</button>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
    {% else %}
    <p class="text-center text-secondary fs-5 mt-5">No products are available!</p>
    {% endif %}
  </section>
{% endblock %}

catalog/templates/catalog/register.html
{% extends "catalog/base_generic.html" %}

{% block page-title %} Get Started {% endblock %}

{% block content %}
  <h1 class="mb-4">Get Started</h1>
  
  <form action="{% url 'catalog:register' %}" method="post">
    {% csrf_token %}
    
    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="first-name" class="form-label">First name</label>
          <input type="text" class="form-control" name="{{ form.first_name.html_name }}" id="first-name" placeholder="e.g. John" value="{{ form.first_name.value|default:'' }}" required>
        </div>
        
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="last-name" class="form-label">Last name</label>
          <input type="text" class="form-control" name="{{ form.last_name.html_name }}" id="last-name" placeholder="e.g. Doe" value="{{ form.last_name.value|default:'' }}" required>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 mb-3">
          <label for="email" class="form-label">Email</label>
          <input type="email" class="form-control" name="{{ form.email.html_name }}" id="email" placeholder="e.g. abc@example.com" value="{{ form.email.value|default:'' }}" required>

          {% if form.email.errors %}
            {% for error in form.email.errors %}
              <p class="form-text text-danger">{{ error }}</p>
            {% endfor %}
          {% endif %}
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" name="{{ form.password.html_name }}" id="password" value="{{ form.password.value|default:'' }}" required>
          
          {% for error in form.non_field_errors %}
            <p class="form-text text-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="col-sm-6 col-lg-4 mb-3">
          <label for="conf-password" class="form-label">Re-enter your password</label>
          <input type="password" class="form-control" name="{{ form.conf_password.html_name }}" id="conf-password" value="{{ form.conf_password.value|default:'' }}" required>
        </div>
      </div>
    </div>
   
    <div class="mb-2">
      <button class="btn btn-primary">Register</button>
    </div>

    <p>Already registered? <a href="{% url 'catalog:login' %}" class="link-primary">Login</a></p>
  </form>
{% endblock %}

catalog/templates/catalog/search.html
{% extends "catalog/base_generic.html" %}

{% block page-title %} Search {% endblock %}

{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'catalog/css/products.css' %}">
{% endblock %}

{% block extra_links %}
  <li><a href="{% url 'catalog:logout' %}" class="nav-link">Logout</a></li>
{% endblock %}

{% block extra_items %}
{% include "catalog/search_form.html" %}
{% endblock %}

{% block content %}
  <h1 class="fw-normal h4">
    {% if product_list %}
      {{ product_list.count }} result{{ product_list.count|pluralize }} found for "{{ q }}"
    {% else %}
      No search query given.
    {% endif %}
  </h1>

  {% if product_list %}
  <div class="container my-5">
      
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-2 g-lg-3">
      {% for product in product_list %}
      <div class="col">
        <div class="card">
          <a href="{{ product.get_absolute_url }}">
            <img class="card-img-top p-2" src="{{ product.photo.url }}" alt="A man wearing blue shirt">
          </a>
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h2 class="card-title h5 m-0">
                <a href="{{ product.get_absolute_url }}" class="link-dark text-decoration-none">{{ product.title }}</a>
              </h2>
              <p class="card-text text-primary lead fw-bold">{{ product.format_price }}</p>
            </div>
            <button class="btn btn-outline-secondary btn-sm w-100">Add to Cart</button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

catalog/templates/catalog/search_form.html
<form action="{% url 'catalog:product-search' %}" method="GET" class="d-flex">
  <input class="form-control ms-4" type="search" name="q" placeholder="Search products" aria-label="Search products">
</form>